spring:
  main:
    print-all-beans: true
  config:
    name: miaosha
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://117.72.72.114:3306/miaosha?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8091
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

redis:
  sdk:
    config:
      host: 117.72.72.114
      port: 6380
      password: 1234
      database: 0
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true
      use-cluster: true
      node: "117.72.72.114:6385,117.72.72.114:6380,117.72.72.114:6381,117.72.72.114:6382,117.72.72.114:6383,117.72.72.114:6384"
#redis:
#  sdk:
#    config:
#      host: 117.72.72.114
#      port: 16379
#      database: 1
#      pool-size: 10
#      min-idle-size: 5
#      idle-timeout: 30000
#      connect-timeout: 5000
#      retry-attempts: 3
#      retry-interval: 1000
#      ping-interval: 60000
#      keep-alive: true
